(ns farn.assets)

(def =assets-static-sprites= 
  [
  "baby-float-1.png"
  "brown-stand-1.png"
  "brown-stand-2.png"
  "brown-talk-blink-1.png"
  "brown-talk-blink-2.png"
  "brown-talk-blink-3.png"
  "brown-talk-noblink-1.png"
  "brown-talk-noblink-2.png"
  "brown-talk-noblink-3.png"
  "green-walk-1.png"
  "green-walk-2.png"
  "pink-crouch-4.png"
  "pink-stand-1.png"
  "pink-stand-2.png"
  "pink-stand-3.png"
  "pink-stand-4.png"
  "pink-walk-1.png"
  "pink-walk-2.png"
  "static-bush-1.png"
  "static-cactus-1.png"
  "static-cactus-2.png"
  "static-cactus-3.png"
  "static-floor-path-big.png"
  "static-floor-path-medium.png"
  "static-floor-path-small.png"
  "static-flower-1.png"
  "static-flower-2.png"
  "static-flower-3.png"
  "static-flower-4.png"
  "static-flower-5.png"
  "static-lump-1.png"
  "static-lump-2.png"
  "static-lump-3.png"
  "static-rock-1.png"
  "static-schroom-1.png"
  "static-schroom-2.png"
  "static-shrub-1.png"
  "static-tree-10.png"
  "static-tree-11.png"
  "static-tree-12.png"
  "static-tree-13.png"
  "static-tree-14.png"
  "static-tree-15.png"
  "static-tree-16.png"
  "static-tree-17.png"
  "static-tree-18.png"
  "static-tree-19.png"
  "static-tree-1.png"
  "static-tree-20.png"
  "static-tree-2.png"
  "static-tree-3.png"
  "static-tree-4.png"
  "static-tree-5.png"
  "static-tree-6.png"
  "static-tree-7.png"
  "static-tree-8.png"
  "static-tree-9.png"
  "static-tree-shrub-brown-1.png"
  "static-tree-shrub-brown-2.png"
  "static-tree-shrub-brown-3.png"
  "static-tree-shrub-brown-4.png"
  "static-tree-shrub-dark-1.png"
  "static-tree-shrub-dark-2.png"
  "static-tree-shrub-dark-3.png"
  "static-tree-shrub-dark-4.png"
  "static-tree-shrub-light-1.png"
  "static-tree-shrub-light-2.png"
  "static-tree-shrub-light-3.png"
  "static-tree-shrub-light-4.png"
  "static-tree-trunk-1.png"
  "static-tree-trunk-2.png"
  "static-tuft-1.png"
  "static-tuft-2.png"
  "static-tuft-3.png" 
])

(def =assets-fonts= ["http://fonts.gstatic.com/s/lobster/v12/cycBf3mfbGkh66G5NhszPQ.woff2"
   "http://fonts.gstatic.com/s/varelaround/v6/APH4jr0uSos5wiut5cpjrugdm0LZdjqr5-oayXSOefg.woff2"
   "http://fonts.gstatic.com/s/shadowsintolighttwo/v4/gDxHeefcXIo-lOuZFCn2xbIfIbZrEcH2WW587lG91II.woff2"])

(def =assets=
  (into =assets-fonts= =assets-static-sprites= ))
